name: ðŸŒŒ Quantum BDI Processing & Security Guard

on:
  push:
    branches: [ main ] # Berjalan setiap kali ada push ke branch main
  repository_dispatch:
    types: [quantum-processing-trigger]
  workflow_dispatch:

jobs:
  security-scan:
    name: ðŸ›¡ï¸  Code Guardian Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: âš¡ Checkout Repository
        uses: actions/checkout@v3
      
      - name: ðŸ§  Jalankan Pemindaian oleh CodeGuardianAgent
        run: |
          python github_actions_quantum/check_secrets.py

  run-quantum-pipeline:
    name: Execute Quantum BDI Pipeline
    needs: security-scan # PENTING! Job ini hanya berjalan JIKA security-scan SUKSES
    runs-on: ubuntu-latest
    steps:
      - name: âš¡ Checkout Repository
        uses: actions/checkout@v3

      - name: âš™ï¸  Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: ðŸ“¦ Install Dependencies
        run: |
          pip install --upgrade pip
          # Menggunakan file requirements.txt
          pip install -r requirements.txt

      - name: ðŸ§ª 1. Run Quantum Belief Processing
        id: belief_processing
        run: |
          python github_actions_quantum/quantum/belief_quantum.py
          BELIEF_FILE=$(ls -t artifacts/belief_data | grep 'belief_summary' | head -n 1)
          echo "belief_output_path=artifacts/belief_data/$BELIEF_FILE" >> $GITHUB_OUTPUT

      - name: ðŸ’¡ 2. Run Quantum Desire Optimization
        id: desire_optimization
        run: |
          python github_actions_quantum/quantum/desire_quantum.py --belief-file ${{ steps.belief_processing.outputs.belief_output_path }}
          DESIRE_FILE=$(ls -t artifacts/desire_data | grep 'desire_summary' | head -n 1)
          echo "desire_output_path=artifacts/desire_data/$DESIRE_FILE" >> $GITHUB_OUTPUT

      - name: ðŸš€ 3. Run Quantum Intention Planning
        id: intention_planning
        run: |
          python github_actions_quantum/quantum/intention_quantum.py --desire-file ${{ steps.desire_optimization.outputs.desire_output_path }}

      - name: ðŸ“ Upload All Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quantum-bdi-results
          path: artifacts/
          retention-days: 5
