name: Quantum BDI Processing & Security Guard

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-scan:
    name: Code Guardian Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Run CodeGuardianAgent Scan
        run: python github_actions_quantum/check_secrets.py

  run-quantum-pipeline:
    name: Execute Quantum BDI Pipeline
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: 1. Run Quantum Belief Processing
        id: belief_processing
        run: |
          python github_actions_quantum/quantum/belief_quantum.py
          BELIEF_FILE=$(ls -t artifacts/belief_data | grep 'belief_summary' | head -n 1)
          echo "belief_output_path=artifacts/belief_data/$BELIEF_FILE" >> $GITHUB_OUTPUT

      - name: 2. Run Quantum Desire Optimization
        id: desire_optimization
        run: |
          python github_actions_quantum/quantum/desire_quantum.py --belief-file ${{ steps.belief_processing.outputs.belief_output_path }}
          DESIRE_FILE=$(ls -t artifacts/desire_data | grep 'desire_summary' | head -n 1)
          echo "desire_output_path=artifacts/desire_data/$DESIRE_FILE" >> $GITHUB_OUTPUT

      - name: 3. Run Quantum Intention Planning
        id: intention_planning
        run: |
          python github_actions_quantum/quantum/intention_quantum.py --desire-file ${{ steps.desire_optimization.outputs.desire_output_path }}

      - name: Upload All Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quantum-bdi-results
          path: artifacts/
          retention-days: 5

  business-analysis:
    name: Business Insight Analysis
    needs: run-quantum-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run BusinessInsightAgent Analysis
        run: python github_actions_quantum/quantum/business_analyzer.py

  evolution-chamber:
    name: Evolution Chamber
    needs: business-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run EvolutionAgent Experiment
        run: python github_actions_quantum/quantum/evolution_chamber.py
