name: Quantum BDI Processing

on:
  repository_dispatch:
    types: [quantum-processing-trigger]
  workflow_dispatch:

jobs:
  run-quantum-pipeline:
    runs-on: ubuntu-latest
    name: Execute Quantum BDI Pipeline
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: ¸  Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: ðŸ“¦ Install Dependencies
        run: |
          pip install --upgrade pip
          pip install qiskit requests numpy pandas scikit-learn networkx

      - name: ðŸ§ª 1. Run Quantum Belief Processing
        id: belief_processing
        run: |
          echo "--- Starting Quantum Belief Processing ---"
          python github_actions_quantum/quantum/belief_quantum.py
          BELIEF_FILE=$(ls -t artifacts/belief_data | grep 'belief_summary' | head -n 1)
          echo "belief_output_path=artifacts/belief_data/$BELIEF_FILE" >> $GITHUB_OUTPUT
          echo "--- Quantum Belief Processing Finished ---"

      - name: ðŸ’¡ 2. Run Quantum Desire Optimization
        id: desire_optimization
        run: |
          echo "--- Starting Quantum Desire Optimization ---"
          python github_actions_quantum/quantum/desire_quantum.py --belief-file ${{ steps.belief_processing.outputs.belief_output_path }}
          DESIRE_FILE=$(ls -t artifacts/desire_data | grep 'desire_summary' | head -n 1)
          echo "desire_output_path=artifacts/desire_data/$DESIRE_FILE" >> $GITHUB_OUTPUT
          echo "--- Quantum Desire Optimization Finished ---"

      - name: ðŸš€ 3. Run Quantum Intention Planning
        id: intention_planning
        run: |
          echo "--- Starting Quantum Intention Planning ---"
          python github_actions_quantum/quantum/intention_quantum.py --desire-file ${{ steps.desire_optimization.outputs.desire_output_path }}
          echo "--- Quantum Intention Planning Finished ---"

      - name: ðŸ“ Upload All Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quantum-bdi-results
          path: artifacts/
          retention-days: 5
