name: Quantum BDI Processing & Security Guard

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Menjalankan patroli kesehatan setiap 15 menit
    - cron: '*/15 * * * *'

jobs:
  security-scan:
    name: Code Guardian Security Scan
    if: github.event_name == 'push' # Hanya berjalan saat ada push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python github_actions_quantum/check_secrets.py

  run-quantum-pipeline:
    name: Execute Quantum BDI Pipeline
    needs: security-scan
    if: github.event_name == 'push' # Hanya berjalan saat ada push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - run: pip install -r requirements.txt
      - id: belief_processing
        run: |
          python github_actions_quantum/quantum/belief_quantum.py
          BELIEF_FILE=$(ls -t artifacts/belief_data | grep 'summary' | head -n 1)
          echo "belief_output_path=artifacts/belief_data/$BELIEF_FILE" >> $GITHUB_OUTPUT
      - id: desire_optimization
        run: |
          python github_actions_quantum/quantum/desire_quantum.py --belief-file ${{ steps.belief_processing.outputs.belief_output_path }}
          DESIRE_FILE=$(ls -t artifacts/desire_data | grep 'summary' | head -n 1)
          echo "desire_output_path=artifacts/desire_data/$DESIRE_FILE" >> $GITHUB_OUTPUT
      - run: python github_actions_quantum/quantum/intention_quantum.py --desire-file ${{ steps.desire_optimization.outputs.desire_output_path }}
      - uses: actions/upload-artifact@v4
        with:
          name: quantum-bdi-results
          path: artifacts/

  business-analysis:
    name: Business Insight Analysis
    needs: run-quantum-pipeline
    if: github.event_name == 'push' # Hanya berjalan saat ada push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python github_actions_quantum/quantum/business_analyzer.py

  evolution-chamber:
    name: Evolution Chamber
    needs: business-analysis
    if: github.event_name == 'push' # Hanya berjalan saat ada push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python github_actions_quantum/quantum/evolution_chamber.py

  self-healing-patrol:
    name: Self-Healing Patrol
    # Berjalan jika ada jadwal ATAU dipicu manual
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests
      - name: Run SelfHealingAgent Patrol
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: python github_actions_quantum/quantum/healing_protocol.py
